CREATE DATABASE FLOWERSTORE
GO

USE FLOWERSTORE
GO

CREATE TABLE EMPLOYEE(
	IDEMP INT IDENTITY(1,1) NOT NULL,
	NAMEEMP NVARCHAR(50),
	PHONE NVARCHAR(50),
	SALARY INT,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(IDEMP)
)
GO

CREATE TABLE SIGNIN(
	IDEMP INT  NOT NULL,
	USERNAME NVARCHAR(50)  NOT NULL,
	PASSWORDSI NVARCHAR(50)  NOT NULL,
	CONSTRAINT PK_IDEMPLOYEE PRIMARY KEY(IDEMP),

	CONSTRAINT FK_IDEMPLOYEE FOREIGN KEY(IDEMP) REFERENCES EMPLOYEE(IDEMP)
)
GO


CREATE TABLE INVENTORY(
	IDPROD INT IDENTITY(1,1) NOT NULL,
	PRODUCT NVARCHAR(50) NOT NULL,
	UNITPRICE INT NOT NULL,
	SOLDQUANTITY INT,
	REMANININGQUANTITY INT,
	TOTALQUANTITY INT,
	CONSTRAINT PK_IDPRODUCT PRIMARY KEY(IDPROD),
)
GO

CREATE TABLE CUSTOMER(
	IDCUS INT IDENTITY(1,1) NOT NULL,
	NAMECUS NVARCHAR(50) NOT NULL,
	GENDER NVARCHAR(50),
	PHONE NVARCHAR(50),
	ADDRESSCUS NVARCHAR(50),
	BIRTHDAY NVARCHAR(50),
	CONSTRAINT PK_IDCUSTOMER PRIMARY KEY(IDCUS),
)
GO



CREATE TABLE SUPPLIER(
	IDSUPP INT IDENTITY(1,1) NOT NULL,
	NAMESUPP NVARCHAR(50),
	PHONE NVARCHAR(50),
	ADDRESSSUPP NVARCHAR(50),
	IDPROD INT FOREIGN KEY REFERENCES INVENTORY(IDPROD) NOT NULL, 
	PRODUCT NVARCHAR(50) NOT NULL,
	QUANTITY INT,
	UNITPRICE INT,
	TOTAL INT,
	SUPPLYDATE NVARCHAR(50),
	CONSTRAINT PK_IDSUPPLY PRIMARY KEY(IDSUPP)
)
GO


CREATE TABLE ORDERS(
	IDOD INT IDENTITY(1,1) NOT NULL,
	IDCUS INT FOREIGN KEY REFERENCES CUSTOMER(IDCUS) NOT NULL,
	CUSTOMER NVARCHAR(50),
	IDPROD INT FOREIGN KEY REFERENCES INVENTORY(IDPROD) NOT NULL, 
	PRODUCT NVARCHAR(50),
	QUANTITY INT NOT NULL,
	UNITPRICE INT NOT NULL,
	TOTALPRICE INT,
	CONSTRAINT PK_IDORDERS PRIMARY KEY(IDOD),
)
GO

CREATE TABLE INVOICE(
	IDINV INT IDENTITY(1,1) NOT NULL,
	IDCUS INT FOREIGN KEY REFERENCES CUSTOMER(IDCUS) NOT NULL,
	CUSTOMER NVARCHAR(50),
	IDOD INT FOREIGN KEY REFERENCES ORDERS(IDOD) NOT NULL, 
	IDEMP INT FOREIGN KEY REFERENCES EMPLOYEE(IDEMP) NOT NULL,
	TOTAL INT,
	INVOICEDATE NVARCHAR(50),
	CONSTRAINT PK_IDINVOICE PRIMARY KEY(IDINV),
)
GO


DROP DATABASE FLOWERSTORE