CREATE DATABASE FLOWERSTORE
GO

USE FLOWERSTORE
GO

CREATE TABLE EMPLOYEE(
	IDEMP INT IDENTITY(1,1) NOT NULL,
	NAMEEMP NVARCHAR(50),
	PHONE NVARCHAR(50),
	SALARY INT,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(IDEMP)
)
GO

CREATE TABLE SIGNIN(
	IDEMP INT  NOT NULL,
	USERNAME NVARCHAR(50)  NOT NULL,
	PASSWORDSI NVARCHAR(50)  NOT NULL,
	CONSTRAINT PK_IDEMPLOYEE PRIMARY KEY(IDEMP),

	CONSTRAINT FK_IDEMPLOYEE FOREIGN KEY(IDEMP) REFERENCES EMPLOYEE(IDEMP)
)
GO

CREATE TABLE SUPPLIER(
	IDSUPP NVARCHAR(50) NOT NULL,
	NAMESUPP NVARCHAR(50),
	PHONE NVARCHAR(50),
	ADDRESSSUPP NVARCHAR(50),
	IDPROD NVARCHAR(50) NOT NULL,
	PRODUCT NVARCHAR(50) NOT NULL,
	QUANTITY INT NOT NULL,
	UNITPRICE INT NOT NULL,
	TOTALPRICE INT,
	SUPPLYDATE NVARCHAR(50),
	CONSTRAINT PK_IDSUPPLY PRIMARY KEY(IDSUPP)
)
GO

CREATE TABLE INVENTORY(
	IDPROD INT IDENTITY(1,1) NOT NULL,
	PRODUCT NVARCHAR(50) NOT NULL,
	UNITPRICE INT NOT NULL,
	SOLDQUANTITY INT,
	REMANININGQUANTITY INT,
	TOTALQUANTITY INT,
	CONSTRAINT PK_IDPRODUCT PRIMARY KEY(IDPROD),
)
GO

CREATE TABLE CUSTOMER(
	IDCUS NVARCHAR(50) NOT NULL,
	NAMECUS NVARCHAR(50) NOT NULL,
	GENDER NVARCHAR(50),
	PHONE NVARCHAR(50),
	ADDRESSCUS NVARCHAR(50),
	PRODUCT NVARCHAR(50) NOT NULL,
	QUANTITY INT NOT NULL,
	UNITPRICE INT NOT NULL,
	PURCHASEDATE NVARCHAR(50),
	CONSTRAINT PK_IDCUSTOMER PRIMARY KEY(IDCUS),
)
GO

CREATE TABLE INVOICE(
	IDINV NVARCHAR(50) NOT NULL,
	CUSTOMER NVARCHAR(50),
	PRODUCT NVARCHAR(50),
	QUANTITY INT,
	UNITPRICE INT,
	TOTAL INT,
	INVOICEDATE NVARCHAR(50),
	CONSTRAINT PK_IDINVOICE PRIMARY KEY(IDINV),
)
GO
